import { Lora, Poppins } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Footer from "./components/Footer";
import Header from "./components/Header";
import GlobalToaster from "@/utils/GlobalToaster";
import { CELITIX_FAV_ICON } from "../../public/assets/images.js";
import Head from "next/head";
import CookieConsent from "./components/CookieConsent";
import ChatLauncher from "./components/Common/ChatLauncher";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-lora",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

// export const metadata = {
//   title: "Celitix",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/assets/Icons/CELITIX FAV ICON.svg",
//   },
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>

        <link rel="icon" href={CELITIX_FAV_ICON} />
      </Head>
      <head>
        {/* <!-- Google Tag Manager --> */}
        <Script
          id="gtm-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
                (function(w,d,s,l,i){
                  w[l]=w[l]||[];w[l].push({
                    'gtm.start': new Date().getTime(),
                    event:'gtm.js'
                  });
                  var f=d.getElementsByTagName(s)[0],
                      j=d.createElement(s),
                      dl=l!='dataLayer'? '&l='+l:'';
                  j.async=true;
                  j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;
                  f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-MMDW54T8');
              `,
          }}
        />
        {/* <!-- End Google Tag Manager --> */}

        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-N25JVKV4MH"
          strategy="afterInteractive"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){ dataLayer.push(arguments); }
            gtag('js', new Date());
            gtag('config', 'G-N25JVKV4MH');
          `}
        </Script>

        {/* Cloudflare Turnstile */}
        <Script
          src="https://challenges.cloudflare.com/turnstile/v0/api.js"
          async
        />

        <Script id="fb-pixel-init" strategy="afterInteractive">
          {`
            !function(f,b,e,v,n,t,s){
              if(f.fbq) return;
              n=f.fbq=function(){
                n.callMethod
                  ? n.callMethod.apply(n, arguments)
                  : n.queue.push(arguments);
              };
              if(!f._fbq) f._fbq = n;
              n.push = n;
              n.loaded = !0;
              n.version = "2.0";
              n.queue = [];
              t = b.createElement(e);
              t.async = true;
              t.src = v;
              s = b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t, s);
            }(
              window,
              document,
              "script",
              "https://connect.facebook.net/en_US/fbevents.js"
            );
            fbq("init", "587446320662611"); 
            fbq("track", "PageView");
          `}
        </Script>
      </head>
      <body className={`${lora.variable} ${poppins.variable}`}>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-MMDW54T8"
            height="0"
            width="0"
          // style="display:none;visibility:hidden"
          ></iframe>
        </noscript>

        {/* Facebook Pixel noscript */}
        <noscript>
          <img
            height="1"
            width="1"
            // style="display:none"
            src="https://www.facebook.com/tr?id=587446320662611&ev=PageView&noscript=1"
          />
        </noscript>
        <GlobalToaster />
        <Header />
        <CookieConsent />
        <main>{children}</main>
        <Footer />
        {/* <ChatLauncher /> */}
        {/* <ChatWindow /> */}
      </body>
    </html>
  );
}
