"use client"
import React, { useEffect } from 'react'
import UniversalButton from '../components/UniversalButton'
// import { Helmet } from 'react-helmet-async'
import { initScrollReveal } from '../../utils/ScrollReveal'

const TermsConditions = () => {
//   useEffect(() => {
//     initScrollReveal();
//   }, []);
  return (
    <div className='bg-[#f7ebfc]'>
      {/* <Helmet>
        <title>Terms & Conditions | Celitix</title>
        <meta name="description" content="Review Celitix’s terms and conditions for using our services and platform. Stay informed about your rights, responsibilities, and service guidelines." /> */}
        {/* <link rel="preload" as="image" href={} crossorigin="anonymous" /> */}
      {/* </Helmet> */}

      {/* 1st */}
      <section className="bg-[#f7ebfc] pt-25 md:pt-35 px-4 sm:px-6 lg:px-20">
        <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-1 items-center justify-center pb-2">
          <div className="space-y-6 box-reveal-bottom">
            <h1 className="text-4xl md:text-5xl lg:text-6xl heading text-center font-bold text-gray-900 leading-tight">
              Celitix <span className="text-transparent bg-clip-text bg-gradient-to-r from-[#2b40b0] to-[#36bae2]"> Terms and conditions </span>
            </h1>
          </div>

          <div className="flex justify-center md:justify-end">
            {/* <img
              src={WhatsApp_Business_Platform}
              alt="Whatsapp icon"
              loading="eager"
              fetchpriority="high"
              crossorigin="anonymous"
              title='WhatsApp Business Platform'
              className="w-full max-w-xs sm:max-w-sm md:max-w-md lg:max-w-lg object-contain box-reveal-bottom"
            /> */}
          </div>
        </div>
      </section>
      {/* 1st */}
      {/* 2st */}
      <div className='bg-linear-to-r from-[#2b3fb067] to-[#36bae270] rounded-xl p-2 md:m-15'>
        <div className='p-10 border bg-white border-gray-300 rounded-lg shadow-sm m-5'>
          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading'>Legal Information</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>These Terms of Service (ToS) are an agreement between Celitix, which term shall, unless it be repugnant to the context or meaning thereof, be deemed to mean and include all its affiliates, subsidiaries, successors and permitted assigns) and any Person who is a user/browser/accessed to the Site, (User), whether or not registered, of any of the services available on the this website (Site).</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>The term 'Person' shall mean and include any individual, corporation, partnership, limited liability company, trust, joint stock company, business, limited liability partnership, trust, unincorporated association, Hindu undivided family, joint venture, organization similar to the foregoing, governmental authority or other entity of any nature whatsoever.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>These ToS shall be read in conjunction with all amendments, additional terms, Privacy Policy, or any other terms that govern the services provided through this product from time to time (together, the Service Agreements).</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>I.REGISTRATION</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span> The User, upon registration and successful completion of the registration formalities/payments (Registration) may avail the use of the paid services on the Site, including the use of APIs and the platform (collectively, referred to as the Services). Registration implies acceptance of the terms of the ToS, additional terms and Privacy Policy as may be in force from time to time, including the terms of payment as may be applicable at the relevant time or at any time thereafter.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> The User hereby declares and agrees that (i) all information (including personal information) provided by the User during Registration is true, genuine and accurate and that the User shall ensure that all such information is current, complete, and true at all times; (ii) the User shall maintain and update the User's registration data, in order to keep such data current, complete and true (iii) the User represents that he/she is of legal age (if the User is an individual) and has the requisite legal standing to form a binding contract with Celitix and is not a person barred from receiving Services under the laws of India or other applicable jurisdiction.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'> <span className='font-bold'>(c)</span> All personal information provided by the User in order to accomplish Registration shall be treated in accordance with the Privacy Policy as may be applicable from time to time. </p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span> Upon Registration, the User will be provided a private account (User Account) and a username and password for such User Account. The User shall be solely responsible for the use and activities conducted through such User Account. The User acknowledges that, in order to regulate access to the Service, his/her authentication depends on the verification of the correct username and password. The User acknowledges and accepts that the User is solely responsible for safeguarding the confidentiality of his/her User Account information (including password(s) and user name(s)) and for any use or misuse of his/her User Account and/or the Site resulting from any third party using a password or user name issued to such User. The User agrees to notify Celitix immediately of any known or suspected unauthorized access to or use of the User's Account, or any other breach of security or misuse of the Site known to or suspected by the User and that Celitix is not responsible for fraud of any person or of other Users of the User's Account.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(e)</span> The User accepts and acknowledges that usage of Credits, if any, granted free of charge by Celitix to the User at the time of Registration or at any other time shall also be subject to the all the terms and conditions of the ToS and other Service Agreements.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>II.USAGE</h2>
          <h3 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'> A. General Conditions of Service</h3>
          <h3 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>1. General Terms</h3>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span> User acknowledges that the Services provided herein are restricted to India territory and to the recipients in India only.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> The User acknowledges and accepts that Celitix may, at its sole discretion, deactivate the User's password and/or User Account, or suspend the User's access to any Service without notice at any time. Further, Celitix reserves the right to remove or cancel any of the Content or prevent the distribution of any Content, without notice and without being obliged to provide any explanation for the same. The User hereby authorizes Celitix to rely on any data, notice, instruction or request furnished by the User to Celitix, or that Celitix reasonably believes to have been furnished by such User.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(c)</span> The User acknowledges and agrees that Celitix acts merely as a facilitator in respect of the Services and shall not be liable or responsible in any manner whatsoever for the Content or any other aspect of such Service.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span> The User agrees that Celitix reserves the right to refuse, deny or otherwise restrict the use of the Services by any User, including the right to terminate the use of any Services by any User without notice at any time for any reason as Celitixin its sole discretion may deem sufficient, or without reason. Celitixshall not be liable in any manner whatsoever for such refusal, restriction or termination of the use of any Services by a User at any time.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(e)</span> The User agrees that unless otherwise indicated, any modification of the Services which alter the way in which the Service can be used and/or the launch of new Services will be subject to, and therefore regulated by the ToS and other relevant Service Agreements.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(f)</span> The User acknowledges and agrees that his/her access to and use of the Site, and any and/or all of the Services of, is at the User's own risk. The User acknowledges that the Service is dependent on telecommunications companies and mobile network providers (Operators) and Celitix makes no guarantees of any kind regarding the dependability, accuracy, security, timeliness or availability of the Site network, or Services. Without limiting the foregoing, Celitix does not make any representations or warranties about the condition, suitability, reliability, availability, completeness, security, timeliness, or accuracy of the information, Software, Services and materials contained on the Site for any purpose. All such information, Software, Services and materials are provided "as is" without warranty of any kind. Celitix hereby disclaims all representations, warranties and conditions, express or implied, with regard to this information, Software, Services or materials, including all implied warranties and conditions of merchantability, fitness for a particular purpose, title and non-infringement.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(g)</span> The User acknowledges and agrees that it shall be solely responsible for ensuring all compliances with the Telecom Regulatory Authority of India's (TRAI) Telecom Commercial Communications Customer Preference Regulations, 2010 (TRAI Regulations) and any and all other regulations, statutes, orders, decisions or law in force from time to time which may be applicable to the use of any of the Services (Law). The User acknowledges and agrees that it shall be solely liable, directly or indirectly, for all damage or loss caused or alleged to be caused to Celitix, by or in connection with any misuse of the Services provided by the Company with respect to pushing any unsolicited commercial communications to subscribers and for any and all other violations of the provisions of the TRAI Regulations or Law.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(h)</span> The User hereby agrees to defend, indemnify and hold harmless and agrees to continue to keep indemnified Celitix, its affiliates, directors, officers, employees etc. without any demur or protest, against any/all losses, damages, actions, proceedings including but not limited to legal expenses with respect to violation of these ToS, or any third-party's rights, (including, without limitation, infringement of any copyright, violation of any proprietary right and invasion of any privacy rights) and also in respect to any action taken by any regulatory body or the Operator or any third party with respect to the misuse of the Services availed from the Company including but not limited to, for the breach of any of the provisions of the TRAI Regulations or breach of Law or for any other reason whatsoever. The User acknowledges and agrees that these obligations will be binding on the User during the entire term of the use of any and/or all of the Services and shall survive any termination of the User's relationship with Celitix or use of the Site.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(i)</span> The User acknowledges that Celitix does not assume any implicit or explicit responsibility for the Content stored and/or published by the User through the Site. The User further accepts and agrees that all declarations and opinions expressed by the User are the sole declarations and opinions of such User and do not necessarily represent Celitix’ opinions. Any person who believes that any Content stored and/or published on the Site or distributed through the Site by any User infringes any law, is kindly requested to contact Celitix at the following email address support@Dove-Soft.com.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(j)</span> The User acknowledges and agrees that all software utilized in connection with the Services (Software) is owned by Celitix (and its group companies) and is protected by the applicable Intellectual Property Laws of India and laws of any other jurisdiction in which such Software is used as may be in force from time to time. The User agrees that it shall not, directly or indirectly, copy, modify, create derivative works, and in any way try to discover the source codes of the Software, sell license or transfer to the third parties any right on the Software. Further the User shall not have any rights over the Software in any manner. The User shall not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, Software, services or benefits obtained from the Site, except as expressly provided herein. The User further agrees that the User shall not reproduce or redistribute any Software and that the User shall not copy or reproduce the Software to any other server or location for further reproduction or redistribution. The User agrees that it shall not decompile, disassemble, reverse engineer or otherwise attempt to discover any trade secret contained in the Site or in any product, Service or Software provided through the Site.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(k)</span> The right to use any Service is limited only to the User. Where the User is a Company, such right shall include its employees, provided that any contraventions by the employees of such Company of the provisions of the ToS or any Service Agreement shall be deemed to be violations by the Company and accordingly for the purposes of the ToS and/or any Service Agreements, the Company shall be liable to Celitix for all such contraventions.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(l)</span> The User agrees that the User shall not use a name in connection with using any of the Services that is confusing or misleading, or otherwise impersonate or deceive anyone with respect to its identity. The User further agrees that the User shall not restrict or inhibit any other User from using and enjoying such other User's rights in the Site or in respect to any Service and should not interfere with or disrupt the Site or servers or any network connected to the Site.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(m)</span> The User agrees and accepts that the User shall not use any of the Services through or in connection with the Site to: </p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(i)</span> rent, lease, license, grant a security interest in, or otherwise transfer the User's rights hereunder to any third party unless otherwise expressly agreed by Celitix;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(ii)</span> defame, libel, slander, impersonate, abuse, harass, threaten, invade the privacy of or otherwise violate or infringe the legal rights (including the rights of privacy and publicity) of any other person;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(iii)</span> conduct, promote or forward illegal contests, pyramid schemes, chain letters, unsolicited or unauthorized advertising, unauthorized promotional materials, unsolicited e-mail ( including "spamming") or multi-level or illegal marketing campaigns;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(iv)</span> harm minors in any way;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(v)</span> publish, post, distribute, disseminate, advertise or link to any content, site, topic, name, material or information which is illegal, inappropriate, profane, defamatory, libelous, slanderous, infringing, obscene, indecent, or which contains nudity or adult content; </p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(vi)</span> software, content or other material protected by intellectual property laws, copyright licenses, rights of privacy or publicity, or other proprietary rights, unless the User owns, or controls such rights or has received all necessary consents for the publication, distribution, or linking of such software and other materials;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(vii)</span> software, content or other material that contains viruses, worms, corrupted files, cracks or that may or are intended to damage the operation of or render inoperable another's computer, hardware, software, security measures or system or other programs written to defeat the security measures of any computer, system or programs including any hardware or Software of Celitix;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(viii)</span> software, content, or other material that constitutes "hate speech", whether directed at an individual or a group, and whether based upon the race, sex, creed, national origin, religious affiliation, sexual orientation or language of such individual or group;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(ix)</span> sell, offer to sell, distribute, promote, facilitate, disseminate or link to any sites for marketing, sales, promotion, facilitation or distribution of: firearms; explosives; ammunition; liquor; tobacco products; illegal gambling (including gambling in connection with sporting events); food that is not packaged or does not comply with all applicable laws for sale to consumers by commercial merchants; illicit drugs, pharmaceuticals and controlled substances; counterfeit, pirated or stolen goods; any goods or services that infringe or otherwise violate a third party's rights including copyright, patent, trademark, or rights of publicity or privacy; goods that are considered indecent, obscene or pornographic; registered or unregistered securities; goods or services that the User cannot legally sell; goods which are misrepresented or which do not in fact exist; fraudulent goods; goods, services or activities that if sold via any of the Services site would cause Celitix to violate any law, statute or regulation; or any other illegal activity;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(x)</span> harvest or otherwise collect information about third parties, including e-mail addresses, without the express consent of such third parties;</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(xi)</span> violate any applicable government laws or regulations.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(n)</span> The User agrees that the Services are provided by Celitix without any implicit or explicit warranty and no advise, suggestion, help, written or verbally, provided by Celitix to the User, shall imply any warranty from Celitix. Celitix cannot be held responsible of any harm coming from the inability to access or use any of the Services, or for the loss of any Content of the User or for any other loss suffered by the User as a result of using the Services. The User agrees and acknowledges that it shall be the sole responsibility of the User to keep a copy of the Content. Celitix declines any responsibility whatsoever for any harm coming from the inability to access the Services, viruses, damaged files, errors, interruption of any of the Service, network problems, non-authorized access, modification of data, merchantability and fitness for a particular purpose or for any other claim whatsoever of a similar nature. Celitix reserves the right to modify any and/or all the Services at any time, even without notice to the User.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(o)</span> The User accepts and acknowledges that Celitix may change any of the Services at any time and from time to time without notice, including terminating the offering of any Service altogether. The User agrees that the User may at any time be barred from accessing any of the Services or from using the Site or from receiving any services or benefits from the Site, if Celitix determines the User to have violated the ToS or any other Service Agreements, if any representation or warranty made by the User is untrue in any respect or if Celitix receives a court order or other legal action relating to the User Account. In addition the User agrees that, if the User violates any of these ToS or any applicable Service Agreement the User shall forfeit all Credits accrued to the User in connection with the Site and there will be no refund of any fees prepaid by the User to Celitix.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(p)</span> The User acknowledges and agrees that links (if any) within the Site may let the User leave the Site and that the linked sites are not under the control of Celitix and that Celitix is not responsible for the contents or operation of such linked sites or any link contained in such linked site, any changes or updates to such sites, or Web casting or any other form of transmission received from any linked site.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(q)</span> The User acknowledges and accepts that Celitix shall not in any event be liable for any direct, indirect, punitive, incidental, special, consequential or exemplary damages or any damages whatsoever including, without limitation: damages for loss of use, data, accounts, revenues or profits, arising out of or in any way connected with the use or performance of the Site or any of the Services, or with the delay or inability to use the Site or any Service and related graphics obtained through the Site; or otherwise arising out of the use of the Site, whether based on contract, tort, negligence, strict liability or otherwise, even if Celitix or any of its suppliers has been advised of the possibility of damages. The User acknowledges that if the User is dissatisfied with any portion of the Site, or with any of the ToS or any other Service Agreement, the User's sole and exclusive remedy is to discontinue using the Site and its related Services. It is clarified that in the event of such discontinuation, the User shall not be entitled to receive any refund of monies paid by such User to Celitix or make any other claims whatsoever against Celitix.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(r)</span> The User confirms and declares that the Services are being availed by the User for itself and the User is not an intermediary acting for and on behalf of a third party.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(s)</span> Celitix reserves the right to suspend the services anytime with or without notice in case of any order/direction by a Statutory Body (State or Central) or Judiciary.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(t)</span> You agree to receive promotional, transactional and commercial communications from Celitix through Call/Email/SMS/RCS.</p>


          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>2. Content</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span> The User shall be responsible for all Content uploaded, displayed, transmitted or otherwise used on this Site or published and/or distributed through this Site by such User and Celitix shall have no responsibility or liability whatsoever in respect of such Content. Celitix reserves the right, but is not obligated, to monitor or to review the Content of the User and to monitor User's compliance with the ToS. Celitix reserves the right in its sole discretion to edit, refuse to post or remove any Content which, in the opinion of Celitix violates the ToS or that Celitix for any other reason may deem unfit or improper to be used on the Site, at any time without notice to the User.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> The User represents and warrants that all Content uploaded or distributed/transmitted through the Site by it is owned by such User, or that such User is otherwise well entitled to display, sell, market or otherwise use such Content. Celitix shall not be liable or responsible in any manner whatsoever in respect of any dispute as to the ownership of such Content or in respect of any other dispute, claim, etc. of any nature whatsoever in respect of such Content. The User further agrees to indemnify and continue to hold indemnified Celitix against any claims of any nature whatsoever in respect of the ownership and use of all such Content.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(c)</span> All Content uploaded or otherwise used on this site must conform to the content rules, if any, provided by Celitix from time to time.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span> The User acknowledges that Celitix does not sell the Content, but rather provides a Service to transfer the Content supplied by the User from the web to mobile and other devices. Celitix does not operate any control, monitor, validation or verification over the Content of the User, and therefore cannot be held responsible for the type of Content which can be found on its platform or transmitted through the platform. However, Celitix shall not be responsible or liable in any manner whatsoever for the authenticity, ownership, accuracy or for any other claim whatsoever in respect of such Content. </p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>3. Payment Terms</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span>  The User agrees that Celitix reserves the right to charge the User for use of any Services at the rate and in the manner as may be decided by Celitix from time to time (Consideration). The User acknowledges and agrees that Celitix shall have no obligation to justify the amount of Consideration charged for any Service or be responsible or liable in any manner whatsoever to the User in respect of such Consideration.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> The User shall pay Consideration for all Services through use of Credit Card, net banking or offline mode by cheque or demand drafts against which Credits will be issued which shall be utilized for availing Services subject to the terms and conditions for the use of such Credits. The User shall pay Consideration in advance for the use of any Services.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(c)</span> Celitix shall not under any circumstances, be liable to refund or otherwise return any money paid by a User for use of the Services, whether by way of purchase of Credits or otherwise, except as specifically provided in these ToS.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span> The Commercials mentioned here are subject to change/modification from time to time depending on the change in commercials offered by Network Operator(s) and or Statutory Body. Such changes shall be communicated to the registered e-mail ID with Celitix or the same shall be communicated on the home page of Celitix website.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>4. Credits  </h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span> "Credit" means one (1) standard short message (SMS) of 160 characters which shall be reflected in the User Account of the relevant User, and "Credits" shall be construed accordingly. A standard text message is 160 characters long (SMS sent using the GSM 3.38 Character set). Users can send longer SMS of upto 918 characters which are split into smaller SMS and later joined at the receiving end which is a mobile. In this scenario, SMS length is calculated for 153 characters as 7 characters are used to concatenate the message when it is delivered to the handset.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'> Unicode allows the support of a much wider character set, and includes most character sets in the world, the standard length of a Unicode message is 63 characters (compared to 160 for GSM). Long messages are supported for Unicode messages as well, and they are in multiples of 63 (compared to 153 for GSM)</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> Any Credit once bought cannot be refunded, encashed or otherwise redeemed by the User except for the use of Services unless specifically stated otherwise in these ToS. If the User opts to close his User Account all Credits accumulated in such User Account will immediately thereafter expire and cease to be valid. If the User Account is closed by Celitix in accordance with the rights granted to Celitix under the ToS or any of the Service Agreements, all Credits accumulated in the User Account of such User shall stand forfeited immediately. Celitix shall not under any circumstances incur any monetary or other liability to the User or any other person in respect of Credits expiration/forfeited as a result of closure of the User Account.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(c)</span> Credits may not be transferred between Users or from one User Account to another User Account of the same User.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span> Celitix reserves the right to refuse and/or cancel the sale of Credits to any User based on its sole discretion.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(e)</span> Celitix reserves the right to withhold the Credits of any User, and/or to not permit such User to use such Credits for such period of time as Celitix may in its sole discretion deem fit, in case if Celitix observes that the User is misusing the Services (which includes but not limits to spamming, phishing etc). User shall not use the services for any unlawful activity (including but not limited to fraudulent transactions, fraudulent communications, phishing, communication to an individual or a group of individuals with an intention to commit any fraud or deceive them).</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(f)</span> Celitix reserves the right to confiscate any Credits of a User in accordance with the provisions of this Agreement (Confiscated Credits). All Confiscated Credits shall stand forfeited immediately and the User shall not have any further monetary or other claim or right and Celitix shall have no liability whatsoever in respect of such Confiscated Credits. Celitix also reserves the right to amend the number of Credits based on the amendment in the cost of each Credit due to change in commercials by Operator/Statutory Body with or without intimation to the User.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(g)</span> Celitix has the right to alter or vary any of the above provisions and change its policies in respect of Credits in the manner that Celitix may, in its sole discretion deem fit, without prior notice to the User and Celitix shall not be liable in any manner whatsoever to the User in the event of such alteration or variation of terms. The User is advised to review the terms of use of Credits periodically so as to remain informed of changes, if any, in Celitix's policies in this regard.</p>


          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>5. Governing Law and Jurisdiction</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>The User and Celitix agree that these ToS shall be governed by the laws of India. The User and Celitix agree that all disputes that may arise from or in connection with theToS shall be subject to the jurisdiction of the Courts of Mumbai, Maharashtra, India.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>6. Miscellaneous</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(a)</span> The User agrees that if any provision of these ToS shall be held to be illegal, invalid or unenforceable, in whole or in part, under any enactment or applicable Law, such provision or part thereof shall to that extent be deemed not to form a part of these ToS, and the legality and enforceability of the remainder of these ToS shall not be affected. These ToS constitute the entire agreement between the User and Celitix with regard to use of the Services and all other written or oral agreements or understandings previously existing between the User and Celitix with respect to such use are hereby superseded and/or cancelled. Celitix's failure, if any, to insist on or enforce strict performance of these ToS shall not be construed as a waiver by Celitix of any provision or any right or future right it has to enforce these ToS, nor shall any course of conduct between Celitix and User or any other party be deemed to modify any provision of these ToS. These ToS shall not be interpreted or construed to confer any rights or remedies on any third parties.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(b)</span> The User agrees not to represent himself/ herself to be a representative, agent, or employee of Celitix and that Celitix will not be liable by reason of any representation, act or omission to act by such User. The User agrees that no joint venture, partnership, employment, or agency relationship exists between the User and Celitix as a result of these ToS or use of the Site.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(c)</span> The User acknowledges and accepts that Celitix's performance of this agreement is subject to existing laws and legal process, and nothing contained in these ToS are in derogation of Celitix's right to comply with governmental, court and law enforcement requests or requirements relating to the use of the Site or information provided to or gathered by Celitix with respect to such use.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(d)</span>Celitix shall provide the services on best effort basis and it takes no responsibility for the delay caused in the Services as the delivery is subject to inter-operator dependencies.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>Use of Service Numbers</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(i)</span> The User acknowledges that Celitix does not guarantee the continued use of any Service Number and that use of such Service Number may be discontinued at any time without notice to the User. If the Service Number of any User is discontinued Celitix shall make all reasonable efforts to provide such User with an alternate Service Number for the continuation of the Services (Alternate Service Number).</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(ii) </span> The User agrees that if Celitix is unable to provide an Alternate Service Number due to any reason whatsoever, Celitix shall have the right to refund the proportionate amount of Credits paid by the User for the use of the Service Number and such refund of Credits by Celitix shall fully and finally settle all liabilities and claims whatsoever of the User in this regard. The User further agrees that the liability of Celitix in the event that Celitix does not provide an Alternate Service Number to the User shall not under any circumstances be in excess of the proportionate amount of Credits paid by the User in respect of the particular Service Number.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 '><span className='font-bold'>(e)</span> The User agrees that if Celitix is unable to provide an Alternate Service Number due to any reason whatsoever, Celitix shall have the right to refund the proportionate amount of Credits paid by the User for the use of the Service Number and such refund of Credits by Celitix shall fully and finally settle all liabilities and claims whatsoever of the User in this regard. The User further agrees that the liability of Celitix in the event that Celitix does not provide an Alternate Service Number to the User shall not under any circumstances be in excess of the proportionate amount of Credits paid by the User in respect of the particular Service Number.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(i)</span> The User shall provide Celitix with a list of recipients (each a Recipient and together the Recipients) of a Promotional Campaign and Celitix shall, in accordance with the terms and conditions push the relevant Promotional Messages to the gateway of the Operator for forwarding to the Recipients.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(ii)</span> The User agrees that Celitix shall only ensure that the Promotional Messages are pushed to the gateway of the Operator through whom such Promotional Messages are transmitted to the Recipients and that Celitix shall not be required to take any further action and shall not bear any further obligation in respect of such Promotional Messages. Celitix does not guarantee the receipt of the Promotional Message by the Recipients and shall not be liable in any manner whatsoever for the failure of delivery of the Promotional Messages to any and/or all the Recipients.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6' ><span className='font-bold'>(iii)</span> The User represents and warrants that all the Recipients listed in the list of Recipients provided to Celitix have consented to receive the relevant Promotional Messages and that pushing of the Promotional Messages to such Recipients shall not constitute a violation or breach of Applicable Law including the TRAI Regulations. In the event that it is found that any of such Recipients has not consented to the Receipt of such Content/ Promotional Message or has objected to the receipt of such Content/Promotional Message for any reason whatsoever, all responsibility and liability in this regard shall rest solely on the User and Celitix shall not be responsible or liable in any manner whatsoever in this regard. The User agrees to indemnify and continue to hold indemnified Celitix from any loss, damage or claim whatsoever in respect of the sending of any Promotional Message or use of any other Service to a Recipient who has not consented to the receipt of such Promotional Message or other Service.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(iv)</span> The User agrees that Celitix reserves the right, but is not obliged, to filter all Promotional Messages and also reserves the right to not push any and/or all Promotional Message to any and/or all Recipients for any reason as Celitix may, in its sole discretion, deem fit. The User further agrees that Celitix shall not be liable to the User or any other party in any manner whatsoever in respect of such decisions taken by Celitix to not push any and/or all the Promotional Messages to any and/or all the Recipients and Celitix shall also not be liable in any manner whatsoever in the event that it does not filter such Promotional Messages.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(v)</span> The User agrees that the relevant Promotional Messages shall be pushed to the gateway of the Operator within the specific time period pre-agreed to between the User and Celitix.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(vi)</span> The User acknowledges and agrees that it shall be solely responsible for ensuring all compliances with the TRAI Regulations. The User acknowledges and agrees that it shall be solely liable, directly or indirectly, for all damage or loss caused or alleged to be caused to Celitix, by or in connection with any misuse of the Services provided by the Company with respect to pushing any commercial communications to subscribers and for any and all other violations of the provisions of the TRAI Regulations.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6' ><span className='font-bold'>(vii)</span> The User hereby agrees to defend, indemnify and hold harmless and agrees to continue to keep indemnified Celitix, its affiliates, directors, officers, employees etc. without any demur or protest, against any/all losses, damages, actions, proceedings including but not limited to legal expenses with respect to any action taken by any Statutory Body or the Operator with respect to the misuse of the Services availed from the Company including but not limited to, for the breach of any of the provisions of the TRAI Regulations during the entire period of the Promotional Campaign and for all periods after the expiry or termination of the relevant Promotional Campaign.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2 ml-6'><span className='font-bold'>(viii)</span> The User agrees that if the User is desirous of terminating any Promotional Campaign it shall provide a request in writing to Celitix for such termination of the relevant Promotional Campaign (PC Termination Request) and Celitix shall subsequent to receipt of such PC Termination Request make all reasonable efforts to terminate the relevant Promotional Campaign at the earliest. The User further agrees that despite making such PC Termination Request, the User shall continue to be liable to make payments of all amounts due to Celitix for Services provided between the time of receipt of PC Termination Request by Celitix and the actual termination of the relevant Promotional Campaign. If, due to any reason whatsoever, Celitix is unable to terminate any Promotional Campaign, the User agrees that it shall be liable to make all payments to Celitix in respect of such Promotional Campaign as if no PC Termination Request had been made by the User. Nothing contained above shall cause or imply any liability of Celitix to the User and the User agrees that it shall indemnify and continue to hold indemnified Celitix in the manner prescribed in the ToS.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(f)</span> For Affiliate Partners and Dual Brand Partners - The entire liability of Celitix for the reasons directly attributable to it and your exclusive remedy for any dispute/difference in connection with the Affiliate Program and the Dual Brand Program shall in no event exceed the applicable Commission payable to You.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(g)</span> Fair Use: The user shall not send more than 100 SMS per day via Email2SMS. The limit is not applicable for dedicated channel users.   </p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>B. APIs</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>In addition to the General Conditions of Service any User of API Services shall be bound by the following terms and conditions:</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(i)</span> The User acknowledges and undertakes that the User shall not have rights over any API offered by Celitix for the User to enhance the options for utilization of Services and such API shall belong to Celitix. Celitix has disclosed the API only for the purpose for utilization of Services by the User. The User undertakes and agrees that it shall not, except with the prior written consent of Celitix: (i) allow or in any manner facilitate or permit the utilization of any APIs by any person other than the User; (ii) develop/create/build any product or service using one or more of the APIs to be used except by the User; (ii) redistribute or reuse any APIs or distribute or sell any products or services developed using any APIs. The User acknowledges and accepts that if it wishes to undertake any of the actions stipulated in (i), (ii) or (iii) above, the same would be subject to the prior written consent of Celitix and subject to specific additional terms and conditions stipulated by Celitix, in its sole discretion, in this regard.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(ii)</span> The User hereby agrees to defend, indemnify and hold harmless and agrees to continue to keep indemnified Celitix, its affiliates, directors, officers, employees etc. without any demur or protest, against any/all losses, damages, actions, proceedings including but not limited to legal expenses with respect to any action taken by any Statutory Body or the Operator with respect to the misuse of the API including but not limited to, for the breach of any of the provisions of the TRAI Regulations or any other Law for the time being in force.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'><span className='font-bold'>(iii)</span> The User agrees that Celitix reserves the right to refuse, deny or otherwise restrict the use of the Services by any User, including the right to terminate the use of any Services by any User without notice at any time for any reason as Celitix in its sole discretion may deem sufficient, or without reason. Celitix shall not be liable in any manner whatsoever for such refusal, restriction or termination of the use of any Services by a User at any time.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>7. Release</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>User hereby releases Celitix, as well as Celitix’s affiliates, founders, directors, employees, subsidiaries, or other legal representative from any claims, demand, damages or other legal action which may arise from Member’s dispute with any person.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>8. Intellectual Property Ownership</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>As between Celitix and User, Celitix will have and retain ownership of all right, title and interest to technology and intellectual property developed by Celitix, its Affiliates and their personnel, whether or not relating to the Patent Rights and Technology.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>9. Survival</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>Any provisions of this agreement which by its terms imposes continuing obligation on User shall survive termination of this agreement.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>10. Severability</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>If any part of this agreement becomes invalid, illegal, or unenforceable such provision shall be severed from this agreement and the parties shall in such an event negotiate in good faith in order to agree the terms of a mutually satisfactory provision to be substituted for the invalid, illegal, or unenforceable provision which as nearly as possible gives effect to their contractual intentions as expressed in this document.</p>



          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>11. Dispute Resolution and Governing Laws</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>The parties shall Endeavour to resolve any dispute or difference arising from this AGREEMENT or any transaction or performance or non-performance under this AGREEMENT, by mutual discussion. Any such dispute or difference, which cannot be so resolved within a period of 30 days then all claims and disputes arising under or relating to this Agreement are to be settled by binding e-arbitration. With an objective resolve the dispute, PDR ORGANIZATION PRIVATE LIMITED (PrivateCourt) shall conduct the e-arbitration and the parties shall be bound by any and all rules of PDR ORGANIZATION PRIVATE LIMITED (PrivateCourt) and any award/decision rendered. Any such arbitration shall be conducted by an experienced arbitrator/lawyer (to be appointed by PDR ORGANIZATION PRIVATE LIMITED (PrivateCourt)) and shall include a written record of the arbitration hearing. Any decision or award as a result of any such arbitration proceeding shall be in writing and shall provide an explanation for all decisions. An award of arbitration may be confirmed/executed in a court of competent jurisdiction. The seat of arbitration shall be Mumbai. Entire Arbitration proceeding will be conducted online through e-filing and video conferencing and award will be provided in physical form on appropriate stamp paper.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>12. Force Majeure:</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>Celitix shall not be liable for any delays or failures in performance resulting from acts beyond its reasonable control including, without limitation, acts of God, acts of war or terrorism, shortage of supply, breakdowns or malfunctions, interruptions or malfunction of computer facilities, or loss of data due to power failures or mechanical difficulties with information storage or retrieval systems, labor difficulties or civil unrest. Notwithstanding the foregoing, in the event of such an occurrence, each party agrees to make a good faith effort to perform its obligations hereunder.</p>

          <h2 className='text-xl md:text-3xl lg:text-3xl font-semibold text-gray-900 heading mt-3'>13. Heading</h2>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'>Heading to this agreement are for convenience only. Heading shall not in way affect the provisions themselves and shall not in any way construed in any way that would limit or otherwise affect the terms of this agreement.</p>
          <p className='text-gray-700 text-base md:text-lg pera lg:text-lg mt-2'> Last updated on 1st March, 2023</p>


        </div>
      </div>
      {/* 2st */}
    </div>
  )
}

export default TermsConditions
